import { Product, Category } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Cordless Power Drill Kit',
    price: 289.00,
    category: Category.TOOLS,
    image: 'https://images.unsplash.com/photo-1617103996702-96ff29b1c467?auto=format&fit=crop&w=800&q=80',
    description: 'High-performance cordless red power drill set. Includes carry case, screwdriver bits, pliers, and essential hand tools.',
    rating: 4.9,
    specs: ['20V Lithium Ion', 'Variable Speed', 'Impact Driver Included'],
  },
  {
    id: 2,
    name: 'Heavy Duty Wheelbarrow',
    price: 145.00,
    category: Category.TOOLS,
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    description: 'Galvanized steel wheelbarrow with pneumatic tire. Ideal for hauling bricks, cement, and garden debris.',
    rating: 4.7,
    specs: ['100L Capacity', 'Steel Frame', 'Pneumatic Tire'],
  },
  {
    id: 3,
    name: 'Door Hinges & Latches Set',
    price: 45.50,
    category: Category.FITTINGS,
    image: 'https://images.unsplash.com/photo-1610520999534-724d8f6e06a6?auto=format&fit=crop&w=800&q=80',
    description: 'Complete set of stainless steel door hinges and security latches. Resistant to rust and wear.',
    rating: 4.6,
    specs: ['Stainless Steel', 'Ball Bearing Hinges', 'Includes Screws'],
  },
  {
    id: 4,
    name: 'Electrical Conduit & PVC Pipes',
    price: 89.00,
    category: Category.PLUMBING_ELECTRICAL,
    image: 'https://images.unsplash.com/photo-1542989916-59332e590e7d?auto=format&fit=crop&w=800&q=80',
    description: 'Assorted bundle of PVC pipes, flexible electrical conduits, and metal fittings for wiring and plumbing projects.',
    rating: 4.5,
    specs: ['20mm & 25mm', 'Flexible PVC', 'EMT Fittings'],
  },
  {
    id: 5,
    name: 'Stainless Steel Nuts & Bolts',
    price: 29.99,
    category: Category.FASTENERS,
    image: 'https://images.unsplash.com/photo-1506671753297-85d13e35c8b2?auto=format&fit=crop&w=800&q=80',
    description: 'Assorted box of hex bolts, nuts, washers, and screws. Essential for mechanical repairs and construction.',
    rating: 4.8,
    specs: ['M4 - M10 Sizes', '304 Stainless Steel', 'Storage Box Included'],
  },
  {
    id: 6,
    name: 'Building Raw Materials (Bricks & Cement)',
    price: 15.00,
    category: Category.BUILDING,
    image: 'https://images.unsplash.com/photo-1590076215667-875d4ef2d7bf?auto=format&fit=crop&w=800&q=80',
    description: 'Standard red clay bricks and cement mix for masonry and construction. Bulk ordering available.',
    rating: 4.5,
    specs: ['Red Clay Bricks', 'Portland Cement', 'Construction Grade'],
  },
];
